on: push

name: Test Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: find_issue_key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          from: commits

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find_issue_key.outputs.issue }}
          transition: "In Progress"
