on: push

name: Test Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Issue Key
        id: find_issue_key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          from: commits

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Mark as In Progress
        uses: atlassian/gajira-transition@master
        if: steps.find_issue_key.outputs.issue != '' && steps.extract_branch.outputs.branch == 'develop'
        with:
          issue: ${{ steps.find_issue_key.outputs.issue }}
          transition: "In Progress"

      - name: Mark as Done
        uses: atlassian/gajira-transition@master
        if: steps.find_issue_key.outputs.issue != '' && steps.extract_branch.outputs.branch == 'main'
        with:
          issue: ${{ steps.find_issue_key.outputs.issue }}
          transition: "Done"

